### ISSUE TITLE
Time out of sync

### ISSUE THREAD

**Issue by snarflakes** [llvllch/btcticker#11]
Time seems to get disconnected (unsync) with a basic wifi blip (i did not do a full router disconnect) i think. This time I had a wifi blip the coin price resumed updating normally, but the time got stuck.  Even if changing coins, which are still updating normally, time is staying stuck seeming to mark the moment of the wifi blip.  Oddly enough this problem occurred but time repaired itself 1 hour later.

I will have to try and run this on your code (this occurred on my fork).

**Comment by snarflakes** [comment]
i will close this until i can duplicate it again.

**Comment by llvllch** [comment]
OK.... I vaguely recall that the Pi doesn't have a clock so until it can
see the internet/ your LAN, the time isn't synced. Others will know better
than me though......
