### ISSUE TITLE
I ran into trouble with missing dependencies.

### ISSUE THREAD

**Issue by Frankenmint** [llvllch/btcticker#18]
I'm running raspbian lite and these are the extra dependencies that I needed to get things running:

```
sudo apt-get install libopenjp2-7
sudo apt-get install libqt5gui5
sudo apt-get install python-scipy
sudo apt install libatlas-base-dev
```

I too used the rc.local script using the pi user to make mine load on boot.

**Comment by llvllch** [comment]
That is really useful..... I'll add it to the troubleshooting section of the readme
