### ISSUE TITLE
raise exception( 'could not determine jetson model' )

### ISSUE THREAD

**Issue by SR00000** [llvllch/btcticker#31]
I get this error whether I install btcticker on the home directory or the e-paper directory. Any assistance would be appreciated!

![piscreen](https://user-images.githubusercontent.com/40726606/108528406-61244480-72a1-11eb-927e-6fa74d9716f4.jpeg)
![piscreen2](https://user-images.githubusercontent.com/40726606/108528408-61244480-72a1-11eb-8d08-f4b1393fe8cf.jpeg)

**Comment by llvllch** [comment]
Hey there….

This isn’t the code throwing the error. It looks like your GPIO module is
complaining. Try updating it maybe?

Good luck!
Martin

**Comment by SR00000** [comment]
Hello!

I ran the following updates already:
    sudo apt-get update
    sudo apt-get install python3-pip
    sudo apt-get install python3-pil
    sudo apt-get install python3-numpy
    sudo pip3 install Jetson.GPIO

It results in that despite having updated all of the above. Is there a preference for where btcticker should be cloned/installed to?

**Comment by llvllch** [comment]
The prompt makes me think it's a Raspberry Pi and you've installed GPIO for a Jetson board.

**Comment by SR00000** [comment]
Im using all the same hardware in the btcticker tutorial (2.7in e-Paper HAT using the Waveshare_epd python module), and I followed the tutorial exactly step by step, so I'm not sure how I installed the GPIO for a different board. Is there an obvious step that wasn't listed in the tutorial because an experienced person would know to do it?

**Comment by llvllch** [comment]
sudo pip3 install Jetson.GPIO

isn't in the tutorial is it?

**Comment by SR00000** [comment]
Yeah at the earlier steps it says "Install the Waveshare Python module following the instructions on their Wiki." and on the wiki it provides that pip3 install command. If you believe that was done in error I can try to uninstall it?

Thanks in advance for responding, been going back and forth with friends for days trying to figure this out.

**Comment by llvllch** [comment]
#python3
    sudo apt-get update
    sudo apt-get install python3-pip
   sudo apt-get install python3-pil
   sudo apt-get install python3-numpy
   sudo pip3 install RPi.GPIO
   sudo pip3 install spidev

**Comment by SR00000** [comment]
Ok I will uninstall everything and start from the beginning using only the Pi steps and I'll report back here.

**Comment by llvllch** [comment]
sudo pip3 uninstall Jetson.GPIO

might work, or maybe just installing the RPi one will overwrite it

**Comment by SR00000** [comment]
That worked! Thank you for your help!

**Comment by llvllch** [comment]
Thats great! Closing....
