### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by MAX-P0W3R** [llvllch/btcticker#40]
Im getting this error even after running `sudo pip install -U numpy` and `sudo pip install -U matplotlib`
Any thoughts?
![image](https://user-images.githubusercontent.com/30239728/113539956-d323c500-9593-11eb-99b9-20eb8e1dec02.png)

**Comment by llvllch** [comment]
Yup! I suspect your matplotib version is the issue. Try reverting it to version 3.0.3.
