### ISSUE TITLE
Rewriting the config.yaml

### ISSUE THREAD

**Issue by Bridsrnotreal** [llvllch/btcticker#46]
Something keeps rewriting config.yaml every cycle, making it impossible to adjust

**Comment by Bridsrnotreal** [comment]
This happened after the ticker stopped working and I found the config.yaml empty

**Comment by llvllch** [comment]
So you edit while the script runs? If you reboot after your edit it should
be fine

That said, I'll look at fixing that annoyance.

Thanks!
