### ISSUE TITLE
IDEA: Speed up the display.

### ISSUE THREAD

**Issue by RattyDAVE** [llvllch/btcticker#47]
the writing to the display is a bit slow. (Well way more than a bit)

This module https://github.com/elad661/rpi_epd2in7 has a much quicker write method.

**Comment by llvllch** [comment]
That's a good idea. 

I vaguely recall that tried this one, thinking the partial refresh would a better way to do it. In the end I opted for the 'official' waveshare module due to the lack of activity on that module.

**Comment by NeilInnes** [comment]
Thoughts on this module @llvllch https://github.com/MarvelousBlack/rpi_epaper ?

Happy to give it a whirl if this module seem ok to you 😄

**Comment by llvllch** [comment]
Yes please. I'm going to add a bit of backoff retry logic to the data pull.
Coingecko seems to throttle during times of high traffic, so I'll try to
make the data pull a little more mindful of that

**Comment by NeilInnes** [comment]
Cool - got it working last night to use this library - partial update for this screen (according to the library) only supports a max area of 255x255 so will need quite a refactor to do this. Leave it with me 😄

**Comment by RattyDAVE** [comment]
I have been looking at this. https://github.com/pskowronek/epaper-clock-and-more/tree/master/epds

This is changes the timings so quicker. About 10x quicker on Black and white screen.

**Comment by NeilInnes** [comment]
I like the backoff idea - this could be:
- Move all the API calls are moved to a central new method
- The method could try the request and on fail (HTTP code, timeout or message):
  - sleep (attempt count * 5 seconds?)
  - Retry (recursively call itself)
  - Increase a retry count variable (passed recursively + 1)
  - On reaching maximum number of retries, return an error (as current functionality)

**Comment by NeilInnes** [comment]
> I have been looking at this. https://github.com/pskowronek/epaper-clock-and-more/tree/master/epds
> 
> This is changes the timings so quicker. About 10x quicker on Black and white screen.

That appears to use FAST mode - from other projects I've read `using fast mode may make your e-paper display permanently unrecoverable damage` 😟

**Comment by RattyDAVE** [comment]
Ahhh.. maybe not then!

**Comment by NeilInnes** [comment]
For a device that isn't on continuously it may be ok - but I'd prefer it to update slower than get fried 😄

**Comment by llvllch** [comment]
This was my issue, on a cycling ticker (more than one coin) the date changes, the token image, the price, and albeit a tiny bit, the sparkline. Throw in the fact that partial refresh often leads to ghosting and needs to fully refreshed every now and again made me think "I'll use the manufacturers code"

E-paper is slow. but on a refresh interval of every 5-10 mins, I barely notice it (unless it's in my line of sight at the time)

**Comment by llvllch** [comment]
> I like the backoff idea - this could be:
> 
>     * Move all the API calls are moved to a central new method
> 
>     * The method could try the request and on fail (HTTP code, timeout or message):
>       
>       * sleep (attempt count * 5 seconds?)
>       * Retry (recursively call itself)
>       * Increase a retry count variable (passed recursively + 1)
>       * On reaching maximum number of retries, return an error (as current functionality)

Pretty much, although it doubles sleep time each count. I've committed my first stab at it.

**Comment by NeilInnes** [comment]
I've got a prototype of this working - I split the image into 2 parts and updated them sequentially. I've tried both alternative edp2in7 libraries too.

However, partial updates only support black+white - not 4 gray mode. This means the logo and spark line end up ghosting over each other (not so much of an issue if you aren't cycling through different coins of course). 😞

**Comment by llvllch** [comment]
e-paper gonna e-paper :)

**Comment by NeilInnes** [comment]
lol - think I'll spend a bit more time looking around, but if there if nothing comes up this may need to be closed under "not feasible"

**Comment by NeilInnes** [comment]
I'm calling this one - I've tried around 6 different libraries for the display. All have issues with partial updates and even the best ones leaving too much ghosting when cycling coins. The only solution here is a different type of display - but then, it would lose it's charm 🥰

**Comment by llvllch** [comment]
A noble effort! My simplistic brain tells me that no one loves Waveshare
screens as much as Waveshare does, so their code is probably aimed at
preserving the hardware.
