### ISSUE TITLE
Request: Any chance of support for epd2in13b_V3 (3 Colour)

### ISSUE THREAD

**Issue by Shaun-Harrison** [llvllch/btcticker#48]
Hello

I have the epd2in13b_V3 which is the same model as used in the tutorial, but the colour version

Was wondering how easy or at all possible to have support for this? 

Possible issues would be that it does have a different package that needs to be loaded, and doesn't have a partial refresh

**Comment by llvllch** [comment]
I imagine the 2in13 code in the repository is a perfect starting point. I don't have one of those displays, so I've not tried it. I may rewrite so that a single script can handle multiple screens if there is enough interest.

**Comment by reddai75** [comment]
it would be great, in bigger screens one can use also the candles graphs
