### ISSUE TITLE
When in either landscape orientation, imaged is mirrored (i.e. reads backwards)

### ISSUE THREAD

**Issue by psychosomatico** [llvllch/btcticker#50]
Hi,

Sorry, I have almost no programming experience and first time using a Pi. I just wanted to try my hand with this cool project. Everything seems to be working except that the image is completely reversed (not inverted like what the 3rd button does). It is like the image is its mirror image. However, this is only in either of the two landscape rotations. When I rotate 90 degrees into portrait, or 180 to portrait the other way, its normal.

Thanks!

**Comment by llvllch** [comment]
Interesting! If you comment out line 236 this will prevent the mirroring.
ie change

image = ImageOps.mirror(image)

to

# image = ImageOps.mirror(image)
in the file btcticker.py

**Comment by psychosomatico** [comment]
Thank you! You rock!

**Comment by lborruto** [comment]
I tried this but getting this error after commenting the line : 

`sudo python3 btcticker.py
  File "btcticker.py", line 242
    tokenimage.close()
             ^
IndentationError: expected an indented block`

**Comment by llvllch** [comment]
Ahhh, that's a python thing. Make sure it's indented correctly.

**Comment by lborruto** [comment]
> ,

Oh ok, didn't know it was so sensitive ! Thanks for the fast answer :)
