### ISSUE TITLE
def Internet

### ISSUE THREAD

**Issue by lexcyn** [llvllch/btcticker#63]
I noticed that with the default internet connectivity check I was getting thousands of DNS checks for google.com, so much so that Google was throttling my connection. I removed the connectivity check from the code since I figure most people will be running this after the Pi is already up and connected.

Or maybe there is a cleaner way to check for connectivity?

**Comment by llvllch** [comment]
That is a really good point, I'll fix that today.

**Comment by llvllch** [comment]
Done, one wait for internet before the main loop. The logic *should* take care of the times it loses internet. Thanks for spotting that. Deep shame.
