### ISSUE TITLE
After 24/36 hrs service stops

### ISSUE THREAD

**Issue by reddai75** [llvllch/btcticker#64]
Hello, 
I have updated btcticker to the latest version, but I still experience a crash (not sure if "crash" is the correct word) every now and then.
I am not a programmer but if there is a way I can contribute in finding the issue I would be happy to help...

**Comment by llvllch** [comment]
By crash, do you mean freeze, or does an error screen show? I made a small
but significant change this morning, try updating to that (and thank you
for the help!)

**Comment by reddai75** [comment]
it depends: for example this morning the pi zero was so slow that I couldn't log in: I inserted username , then after I inserted the password the connection timed out... a couple of days ago I was able to log in but the service was probably stopped or frozen: I checked the status (service btcticker status) and it displayed the last update that occured a couple of hours earlier.
I'll update it over the weekend and let you know! 
Thank you for this project!

**Comment by llvllch** [comment]
Try the new version. Someone kindly pointed out that the main loop was
generating a lot of network traffic. That's fixed now (I think)

**Comment by reddai75** [comment]
Hello, I have tried the new version since Sunday, and since then two crashes occured ... I have put btcticker as a service at startup, and here is what I have just get this morning after service btcticker status... as you can see last update occured  around midnight... then nothing.
![image](https://user-images.githubusercontent.com/17185089/123761905-8d407980-d8c2-11eb-95dc-7090bfcb311f.png)

**Comment by llvllch** [comment]
Check dmesg and /var/log/syslog to see if there are any clues as to what
happened.

**Comment by reddai75** [comment]
quick update: now it runs for a couple of days without problems, but after that every now and then the pi zero led starts blinking and there is no screen refresh for up to even 10 hours or more. Later in the day everything goes back to normal… that’s weird.

**Comment by llvllch** [comment]
That is weird, I've seen the flashes too, but google has nothing about
them. I suspect it could be a power saving mode. I'll leave this open and
keep investigating.
