### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by TheRockaXXX** [llvllch/btcticker#69]
I would like to start the script automatically after boot up. I tried rc.local and also tried to use systemd. Nothing worked. I must confess, I'm new to python and i think there is a problem with the relative location of the imported files to python.
Can someone help me to start the script after boot up?
Thank you!

**Comment by llvllch** [comment]
More likely it's because of missing Python modules. Make sure your systemd
file contains the following line under [Service]
User=pi

**Comment by TheRockaXXX** [comment]
Boom. That was fast and very helpful. Now it works fine! Thank you so much!
