### ISSUE TITLE
Not an issue but a request

### ISSUE THREAD

**Issue by skydiveguy** [llvllch/btcticker#7]
Is there any way to setup this device to run btcticker.py on power up?
I am not able to access it via SSL when at work (blocked) and attaching a keyboard mouse and monitor are cumbersome and time consuming.
Having it run at power up would be a great option.

**Comment by sncsoft** [comment]
There are multiple ways to run python script on the device startup. You can read more, for example, here - https://www.dexterindustries.com/howto/run-a-program-on-your-raspberry-pi-at-startup/
Most of the time I prefer to use method #4. 

sudo -E vim /lib/systemd/system/btcticker.service

[Unit]
Description=Bitcoin Ticker Service
After=multi-user.target

[Service]
Type=idle
ExecStart=/usr/bin/python3 /home/pi/Projects/btcticker/btcticker.py > /home/pi/btcticker.log 2>&1

[Install]
WantedBy=multi-user.target

sudo chmod 644 /lib/systemd/system/btcticker.service
sudo systemctl daemon-reload
sudo systemctl enable btcticker.service
sudo systemctl start btcticker.service
sudo systemctl status btcticker.service

At that point you will probably see some missing Python modules, depends of what modules have been installed globally on your Raspberry. You need to install these modules using apt or pip3. And that's it. :-)

**Comment by skydiveguy** [comment]
Thank you!
