### ISSUE TITLE
Shiba Inu shows incorrect dollar value

### ISSUE THREAD

**Issue by bowersbc** [llvllch/btcticker#70]
Coingecko shows Shiba Inu's value at:
$0.00000644
the btcticker shows it at:
$6.44e-06

**Comment by llvllch** [comment]
They're the same:
https://www.calculatorsoup.com/calculators/math/scientific-notation-converter.php

**Comment by llvllch** [comment]
It is :) The problem with decimal notation is that you end up writing a lot of zeros, therefore small text and .00000001 does not really look ten times bigger than .000000001. If you really want it, it is easy to change in the code.

**Comment by PDM78** [comment]
Sorry for digging up the past but I'd like to know where the code for this is located. Thanks!

**Comment by veebch** [comment]
No problem.... it's just in the print statement, but you'll also have a add a conditional font size based on the number of leading zeros. There's a good reason that science likes that notation :)

**Comment by veebch** [comment]
The code now scales prices rather than uses scientifc notation.... enjoy :)
