### ISSUE TITLE
requirements rpi 404 error

### ISSUE THREAD

**Issue by bowersbc** [llvllch/btcticker#71]
When running this command:
sudo python3 -m pip install -r requirements.txt
it returns the following error:
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/rpi/

When navigating manually to the URL, it does indeed return a 404 Not Found.

**Comment by llvllch** [comment]
The use of sudo on the pip install has been deprecated thanks to some improvements by one of the contributors. Try it again with the improved instructions

**Comment by Kapujino** [comment]
`pip3 install rpi` still gives a 404, this has nothing to do with sudo.
rpi does not exist (anymore) on https://pypi.org/simple

**Comment by llvllch** [comment]
Ah! So it's a pipreqs thing. Fixed! (I think)

**Comment by Kapujino** [comment]
Thanks for this repo and the quick fix :+1:
