### ISSUE TITLE
Warning message 'figure.max_open_warning'

### ISSUE THREAD

**Issue by thorstenbe** [llvllch/btcticker#77]
After 15 minutes I've received the following warning message. This might be an issue if it leads to a memory leak but it might also be just a warning. I'm not so into Python therefore I'm just opening the ticket and if it's no issue at all then it can just be closed 😉

```python3[530]: /home/pi/btcticker/btcticker.py:197: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).```

**Comment by llvllch** [comment]
The closing of images has been a bit of a pain. You may well have came across a bug here. I *think* I fixed it..... try the latest version

**Comment by thorstenbe** [comment]
I checked the `git status` and unfortunately it was already the newest version.

**Comment by llvllch** [comment]
I used close('all') for the exact same warning on another code yesterday: https://github.com/llvllch/stonks/commit/a59061a0da44c3691c26411a95cfaf62b05bcf7c
