### ISSUE TITLE
INFO:root:[Errno 13] Permission denied: '/btcticker/images/spark.png'

### ISSUE THREAD

**Issue by kevinbright** [llvllch/btcticker#8]
I'm the guy from Reddit that was having troubling getting the script to start on reboot.  I decided to try it all over again with a fresh install on a new SD card and now I cannot run the script.  When I try: 

`python3 btcticker.py`

I get 

`INFO:root:[Errno 13] Permission denied: '/btcticker/images/spark.png'`

Any ideas?

**Comment by kevinbright** [comment]
I should also add that when trying to clone the repository using `git clone https://github.com/llvllch/btcticker.git,` I got: 

`fatal: could not create work tree dir 'btcticker': Permission denied`

So I used `sudo git clone https://github.com/llvllch/btcticker.git` and I was able to clone it.  Not sure if that is part of the problem.

**Comment by sncsoft** [comment]
It looks like you are cloning a github repository to the root of your file
system as a root user. You have to clone it in the folder under another
user, like pi. Login as pi (or whatever username you use), create working
folder (I like Projects) -
mkdir ~/Projects
cd ~/Projects
git clone https://github.com/llvllch/btcticker.git
cd btcticker
follow the btcticker installation instructions

.

**Comment by kevinbright** [comment]
You are correct.  I am an idiot.  Feel free to close.  Thanks.
