### ISSUE TITLE
Scale up for a 4.2" waveshare

### ISSUE THREAD

**Issue by Zimbakin** [llvllch/btcticker#81]
Hi, I saw the other link re. 7.2" and the **stonks** app.
However, I prefer the look of your app.

I replaced every instance of `epd2in7` with `epd4in2`
but I just get a thin border around the screen. 4in2 Tests work ok.

Is there any way to simply upscale for a 4.2"? thanks.

**Comment by PDM78** [comment]
Just wondering if you found a solution?

**Comment by Zimbakin** [comment]
I modified the code as above. Then resized all the elements and made some improvements. If the original dev gives me permission, I’m happy to share it.

**Comment by Zimbakin** [comment]
![Uploading 3F6C7BF4-DA56-4EA8-BAD2-4A6D62446DA3.jpeg…]()

**Comment by PDM78** [comment]
Thank you Zimbakin. What is that .jpeg file? It reroutes back to this thread.

**Comment by Zimbakin** [comment]
Tried uploading an image of my 4.2 version. Mobile didn't work for some reason.
[https://drive.google.com/file/d/1h4zB4_ACRvARHb57Q9aXNWMEzUa9tzNo/view?usp=sharing](url)
Hopefully the Dev sees this and grants permission to share.

**Comment by veebch** [comment]
Thanks @Zimbakin ....The link is still misbehaving. If you submit a pull request, I can go through the changes.

It seems like a few people are porting to different screen sizes, there must be a relatively elegant way to take screen dimensions as a parameter and have the code take care of all of the scaling.

**Comment by PDM78** [comment]
Zimbakin & veebch Thank you.

**Comment by PDM78** [comment]
Is there an update to this?
