### ISSUE TITLE
Sorry, a beginner question: how to update the code?

### ISSUE THREAD

**Issue by TheRockaXXX** [llvllch/btcticker#83]
Hi there,
sorry for the noob question. I don't know, how i can update the scripts/librarys etc. used in the project. I installed them a few weeks ago and know i see, that there are some updates. How can i update without a full reinstall?
Thanks!

**Comment by llvllch** [comment]
Hey.... the easiest way is a 'git pull'. Just ssh into the pi, change directory to where the code is and issue the command:
     
      cd btcticker
      git pull
