### ISSUE TITLE
error after approximately 6 hours

### ISSUE THREAD

**Issue by jmdeacon** [llvllch/btcticker#9]
I am using a raspberry pi zero w with the 2.7 screen just as you describe. It runs fine for around 6 hours and then stops working.

The error keeps happening.

Here is a screenshot of the error message.

![IMG-3933](https://user-images.githubusercontent.com/68442055/101973259-9fd7b780-3beb-11eb-9062-1a28d2ee561f.jpg)

**Comment by llvllch** [comment]
That looks like coingekco close the connection. I've not experienced that. Did you change the refresh rate?

I just broadened out the cases where that script falls back to coinapi. Try pulling the latest source and seeing how that behaves after 6h.

**Comment by jmdeacon** [comment]
When I first built my ticker, I had changed the config file to refresh every 60 seconds instead of the default 600 seconds. After reading your reply, I decided to switch it back to 600. Now it has been up and running for nearly 24 hours.

Therefore, it appears that the error occurred from trying to refresh every minute. I'm fine with keeping it at every 10 minutes but if anyone else has this problem, you can suggest they go back to every 10 minutes.

**Comment by llvllch** [comment]
Great!
I imagine it was the coingecko API.... the change I made to the code should now revert to coinapi in that case. Closing the issue for now.

**Comment by tmlee** [comment]
Hey from CoinGecko here, surprised to see how there can be issue if you are only hitting the API once every minute; unless you are somehow making unusually more calls which may be lead to a rate limit problem.

**Comment by llvllch** [comment]
It sounds more likely to be an intermittent internet connection. The code currently checks for internet when it starts and then assumes that it is there after that. 

@tmlee Out of interest....What is the daily limit for api calls to coingekco?

**Comment by tmlee** [comment]
> It sounds more likely to be an intermittent internet connection. The code currently checks for internet when it starts and then assumes that it is there after that.
> 
> @tmlee Out of interest....What is the daily limit for api calls to coingekco?

Its currently a minutely limit of 100 requests, but my suggestion is to keep it at 60 calls or less per minute to be absolute safe due to spikes in the public API

**Comment by llvllch** [comment]
thanks! The ePaper takes a few seconds to refresh, so the code couldn't exceed that if it tried.

**Comment by llvllch** [comment]
> Hey from CoinGecko here, surprised to see how there can be issue if you are only hitting the API once every minute; unless you are somehow making unusually more calls which may be lead to a rate limit problem.

@tmlee Hey.... quick question: Does the coingecko have a way of pulling the price for a specific exchange?
